# Generated by Django 4.2.11 on 2024-05-31 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0003_chat_message_chat'),
    ]

    operations = [
        migrations.AddField(
            model_name='chat',
            name='room_name',
            field=models.CharField(default='', max_length=255, unique=True),
        ),
    ]
