# Generated by Django 4.2.11 on 2024-05-31 11:28

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0004_chat_room_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chat',
            name='created_at',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='message',
            name='created_at',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
